version: '3'
services:
  db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "bin/dev"
    # command: bash -c "bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - 3000:3000
    depends_on:
      - db
      # - selenium_chrome
    tty: true
    stdin_open: true
    environment:
      SELENIUM_DRIVER_URL: http://selenium_chrome:4444/wd/hub
  # ik以下い
  # selenium_chrome:
  #   image: selenium/standalone-chrome
  #   ports:
  #     - "4444:4444"
  #   # ref: https://github.com/seleniumhq-community/docker-seleniarm#--shm-size2g
  #   shm_size: 2gb
volumes:
  mysql_data: