default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  port: 3306

development:
  <<: *default
  host: db
  database: myapp_development
  password: password

test:
  <<: *default
  host: db
  database: myapp_test
  password: password

production:
  <<: *default
  database: <%= ENV['HEROKU_DB_DATABASE_NAME'] %>
  host: <%= ENV['HEROKU_DB_HOST'] %>
  username: <%= ENV['HEROKU_DB_USERNAME'] %>
  password: <%= ENV['HEROKU_DB_PASSWORD'] %>
  # 追記
  url: <%= ENV['JAWSDB_URL'] %>
